export type ProductUnit = "dia" | "hora" | "pieza" | "persona" | "paquete";

export type ProductCategory =
  | "Photo Booths"
  | "Interactive Games"
  | "VR/AR/AI"
  | "Food & Beverage"
  | "Screens & Tech"
  | "Printing & Personalization"
  | "Interactive Screens/Totems"
  | "Development & Services"
  | "Viaticos";

export interface Product {
  id: string;
  hubspotId: string;
  name: string;
  category: ProductCategory;
  unitPrice: number;
  costBase: number;
  unit: ProductUnit;
  description: string;
  hasSetup: boolean;
  setupCost: number;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "Photo Booths",
  "Interactive Games",
  "VR/AR/AI",
  "Food & Beverage",
  "Screens & Tech",
  "Printing & Personalization",
  "Interactive Screens/Totems",
  "Development & Services",
  "Viaticos",
];

export const PRODUCTS_CATALOG: Product[] = [
  // ── Photo Booths ──────────────────────────────────────────────
  {
    id: "pb-photo-booth",
    hubspotId: "",
    name: "Photo Booth",
    category: "Photo Booths",
    unitPrice: 14600,
    costBase: 3800,
    unit: "dia",
    description: "Photobooth clasico con pantalla, camara profesional y entrega digital.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pb-photo-booth-aereo",
    hubspotId: "",
    name: "Photo Booth Aereo",
    category: "Photo Booths",
    unitPrice: 18500,
    costBase: 5200,
    unit: "dia",
    description: "Booth aereo con camara cenital para tomas desde arriba en grupo.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "pb-polaroid",
    hubspotId: "",
    name: "Photo Booth tipo Polaroid",
    category: "Photo Booths",
    unitPrice: 15800,
    costBase: 4200,
    unit: "dia",
    description: "Booth con impresion instantanea en formato Polaroid con marco personalizado.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pb-ar-digital",
    hubspotId: "",
    name: "Photo AR Booth Digital",
    category: "Photo Booths",
    unitPrice: 18000,
    costBase: 5000,
    unit: "dia",
    description: "Booth con realidad aumentada digital, objetos 3D y filtros interactivos.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-photo-ai",
    hubspotId: "",
    name: "Photo AI",
    category: "Photo Booths",
    unitPrice: 19800,
    costBase: 5500,
    unit: "dia",
    description: "Booth con inteligencia artificial para generar fondos y estilos artisticos.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-ipad-digital",
    hubspotId: "",
    name: "Ipad Booth Digital",
    category: "Photo Booths",
    unitPrice: 14600,
    costBase: 3800,
    unit: "dia",
    description: "Booth digital con iPad para fotos y GIFs con branding personalizado.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pb-mirror",
    hubspotId: "",
    name: "Mirror Booth",
    category: "Photo Booths",
    unitPrice: 18500,
    costBase: 5200,
    unit: "dia",
    description: "Espejo interactivo de cuerpo completo con animaciones tactiles e impresion.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "pb-cabina-cerrada-ipad",
    hubspotId: "",
    name: "Cabina Cerrada con Ipad Booth",
    category: "Photo Booths",
    unitPrice: 19200,
    costBase: 5800,
    unit: "dia",
    description: "Cabina cerrada con cortina, iPad Booth, iluminacion profesional e impresion.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "pb-calidoscopio",
    hubspotId: "",
    name: "Calidoscopio Booth",
    category: "Photo Booths",
    unitPrice: 17500,
    costBase: 4800,
    unit: "dia",
    description: "Booth con efecto calidoscopio en video y foto para resultados artisticos.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-doble-exposicion",
    hubspotId: "",
    name: "Doble Exposicion Booth Digital",
    category: "Photo Booths",
    unitPrice: 16800,
    costBase: 4500,
    unit: "dia",
    description: "Booth digital con efecto de doble exposicion artistica en tiempo real.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-collage-digital",
    hubspotId: "",
    name: "Collage Digital con Ipad Booth Digital",
    category: "Photo Booths",
    unitPrice: 16500,
    costBase: 4200,
    unit: "dia",
    description: "Booth con iPad que genera collages digitales personalizados en tiempo real.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pb-cartoon",
    hubspotId: "",
    name: "Cartoon Booth Digital",
    category: "Photo Booths",
    unitPrice: 17000,
    costBase: 4500,
    unit: "dia",
    description: "Booth digital que transforma fotos en estilo cartoon o ilustracion.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-mosaico-digital",
    hubspotId: "",
    name: "Mosaico Digital con Ipad Booth",
    category: "Photo Booths",
    unitPrice: 18000,
    costBase: 5000,
    unit: "dia",
    description: "Booth con iPad que contribuye fotos a un mosaico digital en pantalla grande.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "pb-mosaico-fisico-25x25",
    hubspotId: "",
    name: "Mosaico Fisico 25x25",
    category: "Photo Booths",
    unitPrice: 22000,
    costBase: 7000,
    unit: "dia",
    description: "Mosaico fisico impreso de 25x25 pulgadas compuesto por fotos de invitados.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "pb-mosaico-fisico-30x20",
    hubspotId: "",
    name: "Mosaico Fisico 30x20",
    category: "Photo Booths",
    unitPrice: 24000,
    costBase: 7500,
    unit: "dia",
    description: "Mosaico fisico impreso de 30x20 pulgadas compuesto por fotos de invitados.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "pb-mosaico-fisico-54x36",
    hubspotId: "",
    name: "Mosaico Fisico 54x36",
    category: "Photo Booths",
    unitPrice: 28000,
    costBase: 9000,
    unit: "dia",
    description: "Mosaico fisico gran formato de 54x36 pulgadas compuesto por fotos de invitados.",
    hasSetup: true,
    setupCost: 5500,
  },
  {
    id: "pb-instaprint",
    hubspotId: "",
    name: "Instaprint",
    category: "Photo Booths",
    unitPrice: 16500,
    costBase: 4500,
    unit: "dia",
    description: "Impresion instantanea de fotos con hashtag de redes sociales del evento.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pb-long-exposure",
    hubspotId: "",
    name: "Photo Long Exposure",
    category: "Photo Booths",
    unitPrice: 17500,
    costBase: 4800,
    unit: "dia",
    description: "Booth con efecto de larga exposicion y light painting interactivo.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-photo-proyector",
    hubspotId: "",
    name: "Photo Proyector",
    category: "Photo Booths",
    unitPrice: 18000,
    costBase: 5000,
    unit: "dia",
    description: "Booth con proyeccion de fondos inmersivos y escenarios virtuales.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "pb-filtro-ai-booth",
    hubspotId: "",
    name: "Filtro AI Booth",
    category: "Photo Booths",
    unitPrice: 19500,
    costBase: 5500,
    unit: "dia",
    description: "Booth con filtros generados por inteligencia artificial en tiempo real.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-multicam-180",
    hubspotId: "",
    name: "Multicamara 180",
    category: "Photo Booths",
    unitPrice: 24000,
    costBase: 7500,
    unit: "dia",
    description: "Arreglo de multiples camaras para efecto bullet-time 180 grados.",
    hasSetup: true,
    setupCost: 5500,
  },
  {
    id: "pb-multicam-360",
    hubspotId: "",
    name: "Multicamara 360",
    category: "Photo Booths",
    unitPrice: 28000,
    costBase: 9000,
    unit: "dia",
    description: "Arreglo de multiples camaras para efecto bullet-time 360 grados completo.",
    hasSetup: true,
    setupCost: 6500,
  },
  {
    id: "pb-jump-booth",
    hubspotId: "",
    name: "Jump Booth",
    category: "Photo Booths",
    unitPrice: 17000,
    costBase: 4500,
    unit: "dia",
    description: "Booth que captura fotos en el momento exacto del salto con fondo personalizado.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pb-vogue-booth",
    hubspotId: "",
    name: "Estructura Vogue Booth",
    category: "Photo Booths",
    unitPrice: 22000,
    costBase: 7000,
    unit: "dia",
    description: "Estructura premium estilo portada de revista Vogue con iluminacion profesional.",
    hasSetup: true,
    setupCost: 5000,
  },

  // ── Interactive Games ─────────────────────────────────────────
  {
    id: "ig-batak-pared",
    hubspotId: "",
    name: "Batak Pared (1 tablero)",
    category: "Interactive Games",
    unitPrice: 18500,
    costBase: 5000,
    unit: "dia",
    description: "Panel interactivo de pared con luces LED para prueba de reflejos y velocidad.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-batak-tubular",
    hubspotId: "",
    name: "Batak Tubular (1 tablero)",
    category: "Interactive Games",
    unitPrice: 19800,
    costBase: 5500,
    unit: "dia",
    description: "Version tubular del Batak con estructura autoportante y efectos de sonido.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "ig-batak-piso",
    hubspotId: "",
    name: "Batak de Piso",
    category: "Interactive Games",
    unitPrice: 18000,
    costBase: 4800,
    unit: "dia",
    description: "Batak de piso con sensores de pisada y luces LED interactivas.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-balance-challenge",
    hubspotId: "",
    name: "Balance Challenge",
    category: "Interactive Games",
    unitPrice: 19500,
    costBase: 5500,
    unit: "dia",
    description: "Plataforma de equilibrio digital con pantalla y ranking en tiempo real.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-super-kick",
    hubspotId: "",
    name: "Super Kick",
    category: "Interactive Games",
    unitPrice: 22000,
    costBase: 6500,
    unit: "dia",
    description: "Porteria interactiva que mide la velocidad y precision de tiro con sensores.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "ig-sub-soccer",
    hubspotId: "",
    name: "Sub Soccer",
    category: "Interactive Games",
    unitPrice: 16800,
    costBase: 4200,
    unit: "dia",
    description: "Futbolito de mesa profesional con iluminacion LED y branding.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "ig-reflejos",
    hubspotId: "",
    name: "Juego de Reflejos",
    category: "Interactive Games",
    unitPrice: 17000,
    costBase: 4500,
    unit: "dia",
    description: "Panel de botones iluminados para medir tiempo de reaccion y reflejos.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "ig-fuerza",
    hubspotId: "",
    name: "Juego de Fuerza",
    category: "Interactive Games",
    unitPrice: 18000,
    costBase: 4800,
    unit: "dia",
    description: "Maquina de prueba de fuerza con sensor de impacto y ranking digital.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "ig-jump-score",
    hubspotId: "",
    name: "Jump Score",
    category: "Interactive Games",
    unitPrice: 19500,
    costBase: 5500,
    unit: "dia",
    description: "Plataforma de salto con sensor que mide altura y genera ranking en pantalla.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-magic-sensor",
    hubspotId: "",
    name: "Magic Sensor",
    category: "Interactive Games",
    unitPrice: 17500,
    costBase: 4800,
    unit: "dia",
    description: "Juego interactivo con sensores de movimiento y proyeccion en piso.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-pulse-challenge",
    hubspotId: "",
    name: "Pulse Challenge",
    category: "Interactive Games",
    unitPrice: 16800,
    costBase: 4200,
    unit: "dia",
    description: "Reto de pulso electronico con medicion de fuerza y ranking digital.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "ig-dominadas",
    hubspotId: "",
    name: "Dominadas",
    category: "Interactive Games",
    unitPrice: 18000,
    costBase: 5000,
    unit: "dia",
    description: "Barra de dominadas con sensor de conteo automatico y ranking en pantalla.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "ig-football-balance",
    hubspotId: "",
    name: "Football Balance",
    category: "Interactive Games",
    unitPrice: 18000,
    costBase: 5000,
    unit: "dia",
    description: "Plataforma de equilibrio con balon que mide estabilidad y coordinacion.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "ig-futbolito-vr",
    hubspotId: "",
    name: "Futbolito VR",
    category: "Interactive Games",
    unitPrice: 22000,
    costBase: 6500,
    unit: "dia",
    description: "Futbolito de mesa con experiencia de realidad virtual integrada.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "ig-car-race",
    hubspotId: "",
    name: "Car Race",
    category: "Interactive Games",
    unitPrice: 20000,
    costBase: 6000,
    unit: "dia",
    description: "Simulador de carreras con volante, pedales y pantalla inmersiva.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "ig-caminadora-pelotas",
    hubspotId: "",
    name: "Caminadora de Pelotas con Speed Test",
    category: "Interactive Games",
    unitPrice: 24000,
    costBase: 7500,
    unit: "dia",
    description: "Caminadora de pelotas con medicion de velocidad y ranking digital.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "ig-caminadora-magic",
    hubspotId: "",
    name: "Caminadora Magic Screen",
    category: "Interactive Games",
    unitPrice: 25000,
    costBase: 8000,
    unit: "dia",
    description: "Caminadora con pantalla inmersiva y escenarios virtuales interactivos.",
    hasSetup: true,
    setupCost: 5500,
  },
  {
    id: "ig-bicicleta-digital",
    hubspotId: "",
    name: "Bicicleta Digital Test",
    category: "Interactive Games",
    unitPrice: 22000,
    costBase: 6500,
    unit: "dia",
    description: "Bicicleta fija con pantalla digital interactiva y retos de velocidad.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "ig-multiball-led",
    hubspotId: "",
    name: "Multiball Game con Pantalla LED",
    category: "Interactive Games",
    unitPrice: 28000,
    costBase: 8500,
    unit: "dia",
    description: "Juego multiball interactivo con pantalla LED de gran formato.",
    hasSetup: true,
    setupCost: 5500,
  },
  {
    id: "ig-multiball-proyector",
    hubspotId: "",
    name: "Multiball Game con Proyector",
    category: "Interactive Games",
    unitPrice: 24000,
    costBase: 7000,
    unit: "dia",
    description: "Juego multiball interactivo con proyeccion en pared.",
    hasSetup: true,
    setupCost: 4500,
  },

  // ── VR/AR/AI ──────────────────────────────────────────────────
  {
    id: "vr-bubblehead-ai",
    hubspotId: "",
    name: "Bubblehead Booth AI Digital",
    category: "VR/AR/AI",
    unitPrice: 28000,
    costBase: 8000,
    unit: "dia",
    description: "Caricaturas 3D generadas por IA a partir de foto del invitado.",
    hasSetup: true,
    setupCost: 5000,
  },
  {
    id: "vr-meta-human-atlas",
    hubspotId: "",
    name: "Meta Humans - Atlas o Bit",
    category: "VR/AR/AI",
    unitPrice: 35000,
    costBase: 12000,
    unit: "dia",
    description: "Avatar digital hiperrealista (Atlas o Bit) con seguimiento facial en tiempo real.",
    hasSetup: true,
    setupCost: 8000,
  },
  {
    id: "vr-meta-human-dax",
    hubspotId: "",
    name: "Meta Humans - Dax o Eddison",
    category: "VR/AR/AI",
    unitPrice: 35000,
    costBase: 12000,
    unit: "dia",
    description: "Avatar digital inteligente (Dax o Eddison) con conversacion AI y gestos naturales.",
    hasSetup: true,
    setupCost: 8000,
  },
  {
    id: "vr-chipp-meta",
    hubspotId: "",
    name: "Chipp Meta",
    category: "VR/AR/AI",
    unitPrice: 32000,
    costBase: 10000,
    unit: "dia",
    description: "Experiencia con Chipp Meta, avatar interactivo con IA conversacional.",
    hasSetup: true,
    setupCost: 7000,
  },
  {
    id: "vr-holograma-s",
    hubspotId: "",
    name: "Holograma S",
    category: "VR/AR/AI",
    unitPrice: 32000,
    costBase: 10000,
    unit: "dia",
    description: "Pantalla holografica 3D tamano estandar con contenido personalizado flotante.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "vr-holograma-xl",
    hubspotId: "",
    name: "Holograma XL",
    category: "VR/AR/AI",
    unitPrice: 45000,
    costBase: 15000,
    unit: "dia",
    description: "Holograma de gran formato para escenarios y presentaciones ejecutivas.",
    hasSetup: true,
    setupCost: 10000,
  },
  {
    id: "vr-holograma-xl-filtro-ai",
    hubspotId: "",
    name: "Holograma XL con Filtro AI",
    category: "VR/AR/AI",
    unitPrice: 52000,
    costBase: 18000,
    unit: "dia",
    description: "Holograma XL con filtros de inteligencia artificial integrados en tiempo real.",
    hasSetup: true,
    setupCost: 12000,
  },
  {
    id: "vr-credenciales-ai",
    hubspotId: "",
    name: "Credenciales AI",
    category: "VR/AR/AI",
    unitPrice: 26000,
    costBase: 7500,
    unit: "dia",
    description: "Generacion de credenciales personalizadas con IA y foto del asistente.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "vr-ar-treasure-hunt",
    hubspotId: "",
    name: "AR Treasure Hunt",
    category: "VR/AR/AI",
    unitPrice: 38000,
    costBase: 12000,
    unit: "dia",
    description: "Busqueda del tesoro con realidad aumentada en el venue del evento.",
    hasSetup: true,
    setupCost: 8000,
  },
  {
    id: "vr-dibujo-ai",
    hubspotId: "",
    name: "Dibujo AI (Drawing)",
    category: "VR/AR/AI",
    unitPrice: 28000,
    costBase: 8500,
    unit: "dia",
    description: "Estacion de dibujo con inteligencia artificial que completa y estiliza ilustraciones.",
    hasSetup: true,
    setupCost: 5000,
  },
  {
    id: "vr-graffiti-booth",
    hubspotId: "",
    name: "Graffiti Booth",
    category: "VR/AR/AI",
    unitPrice: 26000,
    costBase: 7500,
    unit: "dia",
    description: "Booth de graffiti digital con spray virtual y lienzo interactivo.",
    hasSetup: true,
    setupCost: 5000,
  },
  {
    id: "vr-cancion-ai",
    hubspotId: "",
    name: "Cancion AI",
    category: "VR/AR/AI",
    unitPrice: 30000,
    costBase: 9000,
    unit: "dia",
    description: "Generacion de canciones personalizadas con inteligencia artificial en el evento.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "vr-fortuna-ai",
    hubspotId: "",
    name: "Fortuna AI",
    category: "VR/AR/AI",
    unitPrice: 24000,
    costBase: 7000,
    unit: "dia",
    description: "Experiencia de fortuna y predicciones generadas por inteligencia artificial.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "vr-mixta",
    hubspotId: "",
    name: "VR Mixta",
    category: "VR/AR/AI",
    unitPrice: 28000,
    costBase: 8500,
    unit: "dia",
    description: "Experiencia de realidad virtual mixta con interaccion en el mundo real.",
    hasSetup: true,
    setupCost: 5000,
  },
  {
    id: "vr-camara-ai",
    hubspotId: "",
    name: "Camara AI",
    category: "VR/AR/AI",
    unitPrice: 22000,
    costBase: 6500,
    unit: "dia",
    description: "Camara con inteligencia artificial para efectos visuales en tiempo real.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "vr-photo-drink",
    hubspotId: "",
    name: "Photo Drink",
    category: "VR/AR/AI",
    unitPrice: 24000,
    costBase: 7500,
    unit: "dia",
    description: "Impresion de fotos comestibles sobre la superficie de bebidas y cocktails.",
    hasSetup: true,
    setupCost: 4000,
  },

  // ── Screens & Tech ────────────────────────────────────────────
  {
    id: "st-mesa-interactiva",
    hubspotId: "",
    name: "Mesa Interactiva con Triggers",
    category: "Screens & Tech",
    unitPrice: 28000,
    costBase: 8500,
    unit: "dia",
    description: "Mesa tactil interactiva con triggers fisicos y contenido personalizado.",
    hasSetup: true,
    setupCost: 5000,
  },
  {
    id: "st-esferas-led",
    hubspotId: "",
    name: "Esferas LED",
    category: "Screens & Tech",
    unitPrice: 20000,
    costBase: 6500,
    unit: "dia",
    description: "Esferas LED programables para shows y decoracion de impacto visual.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "st-cortina-led",
    hubspotId: "",
    name: "Cortina LED",
    category: "Screens & Tech",
    unitPrice: 22000,
    costBase: 7000,
    unit: "dia",
    description: "Cortina de tiras LED programables para fondo o decoracion interactiva.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "st-3d-leds",
    hubspotId: "",
    name: "3D LEDs",
    category: "Screens & Tech",
    unitPrice: 28000,
    costBase: 9000,
    unit: "dia",
    description: "Abanico holografico 3D LED para displays de producto y logos flotantes.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "st-brazo-robotico",
    hubspotId: "",
    name: "Brazo Robotico",
    category: "Screens & Tech",
    unitPrice: 38000,
    costBase: 12000,
    unit: "dia",
    description: "Brazo robotico programable para activaciones, servicio o performance.",
    hasSetup: true,
    setupCost: 7000,
  },
  {
    id: "st-mouse-3d",
    hubspotId: "",
    name: "Mouse 3D",
    category: "Screens & Tech",
    unitPrice: 22000,
    costBase: 6500,
    unit: "dia",
    description: "Controlador 3D interactivo para exploracion de modelos y escenas virtuales.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "st-centurion-robot",
    hubspotId: "",
    name: "Centurion Robot Humanoide",
    category: "Screens & Tech",
    unitPrice: 45000,
    costBase: 15000,
    unit: "dia",
    description: "Robot humanoide interactivo para recepcion, entretenimiento y activaciones.",
    hasSetup: true,
    setupCost: 8000,
  },
  {
    id: "st-conteo-personas",
    hubspotId: "",
    name: "Conteo de Personas",
    category: "Screens & Tech",
    unitPrice: 18000,
    costBase: 5500,
    unit: "dia",
    description: "Sistema de conteo de personas en tiempo real con dashboard y reportes.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "st-live-streaming",
    hubspotId: "",
    name: "Live Streaming",
    category: "Screens & Tech",
    unitPrice: 22000,
    costBase: 7000,
    unit: "dia",
    description: "Transmision en vivo del evento con equipo profesional y operador.",
    hasSetup: true,
    setupCost: 4500,
  },
  {
    id: "st-patch-experience",
    hubspotId: "",
    name: "Patch Experience",
    category: "Screens & Tech",
    unitPrice: 24000,
    costBase: 7500,
    unit: "dia",
    description: "Experiencia interactiva con parches NFC y contenido digital personalizado.",
    hasSetup: true,
    setupCost: 5000,
  },

  // ── Food & Beverage ───────────────────────────────────────────
  {
    id: "fb-coffee-print-barra",
    hubspotId: "",
    name: "Coffee Print con Barra de Cafe Gourmet",
    category: "Food & Beverage",
    unitPrice: 22000,
    costBase: 8500,
    unit: "dia",
    description: "Impresion personalizada sobre espuma de cafe latte con barra de cafe gourmet completa.",
    hasSetup: true,
    setupCost: 4000,
  },
  {
    id: "fb-barra-cafe-50",
    hubspotId: "",
    name: "Barra de Cafe Gourmet 50 personas",
    category: "Food & Beverage",
    unitPrice: 16500,
    costBase: 6000,
    unit: "dia",
    description: "Barra de cafe gourmet con barista profesional para 50 personas.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "fb-barra-cafe-100",
    hubspotId: "",
    name: "Barra de Cafe Gourmet 100 personas",
    category: "Food & Beverage",
    unitPrice: 20000,
    costBase: 7500,
    unit: "dia",
    description: "Barra de cafe gourmet con barista profesional para 100 personas.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "fb-barra-refresh",
    hubspotId: "",
    name: "Barra Refresh 100 Personas",
    category: "Food & Beverage",
    unitPrice: 19500,
    costBase: 7000,
    unit: "dia",
    description: "Barra de bebidas frescas, smoothies y jugos personalizados para 100 personas.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "fb-cotton-candy",
    hubspotId: "",
    name: "Cotton Candy Machine",
    category: "Food & Beverage",
    unitPrice: 14600,
    costBase: 4500,
    unit: "dia",
    description: "Maquina de algodon de azucar con colores y sabores personalizados.",
    hasSetup: true,
    setupCost: 2000,
  },
  {
    id: "fb-paletas-hielo",
    hubspotId: "",
    name: "Paletas de Hielo 100 piezas",
    category: "Food & Beverage",
    unitPrice: 15500,
    costBase: 5500,
    unit: "paquete",
    description: "100 paletas de hielo artesanales con sabores y branding personalizado.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "fb-leche-vegetal",
    hubspotId: "",
    name: "Leche Vegetal",
    category: "Food & Beverage",
    unitPrice: 2500,
    costBase: 1200,
    unit: "dia",
    description: "Opcion de leche vegetal (almendra, avena, soya) para barras de cafe.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "fb-photo-drink-100",
    hubspotId: "",
    name: "Photo Drink 100 piezas",
    category: "Food & Beverage",
    unitPrice: 18000,
    costBase: 6500,
    unit: "paquete",
    description: "100 bebidas con impresion de foto comestible personalizada.",
    hasSetup: true,
    setupCost: 3500,
  },

  // ── Printing & Personalization ────────────────────────────────
  {
    id: "pr-digital-print",
    hubspotId: "",
    name: "Digital Print",
    category: "Printing & Personalization",
    unitPrice: 16500,
    costBase: 4800,
    unit: "dia",
    description: "Estacion de impresion digital de alta calidad para fotos y graficos.",
    hasSetup: true,
    setupCost: 3000,
  },
  {
    id: "pr-maquina-laser",
    hubspotId: "",
    name: "Maquina Laser",
    category: "Printing & Personalization",
    unitPrice: 18000,
    costBase: 5500,
    unit: "dia",
    description: "Maquina de grabado laser para personalizacion de objetos en el evento.",
    hasSetup: true,
    setupCost: 3500,
  },
  {
    id: "pr-pines",
    hubspotId: "",
    name: "Impresion en Pines",
    category: "Printing & Personalization",
    unitPrice: 15500,
    costBase: 4500,
    unit: "dia",
    description: "Maquina de pines/botones personalizados con foto del invitado.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pr-pvc",
    hubspotId: "",
    name: "Impresion en PVC",
    category: "Printing & Personalization",
    unitPrice: 14500,
    costBase: 4200,
    unit: "dia",
    description: "Impresion sobre tarjetas o credenciales de PVC personalizadas.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pr-impresion-4x6",
    hubspotId: "",
    name: "Impresiones de 4x6",
    category: "Printing & Personalization",
    unitPrice: 8000,
    costBase: 2500,
    unit: "paquete",
    description: "Paquete de impresiones fotograficas en formato 4x6 pulgadas.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-impresion-6x8",
    hubspotId: "",
    name: "Impresiones de 6x8",
    category: "Printing & Personalization",
    unitPrice: 10000,
    costBase: 3200,
    unit: "paquete",
    description: "Paquete de impresiones fotograficas en formato 6x8 pulgadas.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-sticker-5x5",
    hubspotId: "",
    name: "Impresiones Sticker 5x5",
    category: "Printing & Personalization",
    unitPrice: 8500,
    costBase: 2800,
    unit: "paquete",
    description: "Paquete de stickers personalizados de 5x5 cm con diseno del evento.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-polaroid",
    hubspotId: "",
    name: "Impresiones tipo Polaroid",
    category: "Printing & Personalization",
    unitPrice: 9000,
    costBase: 3000,
    unit: "paquete",
    description: "Paquete de impresiones con formato y marco estilo Polaroid.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-tattoo-print",
    hubspotId: "",
    name: "Tattoo Print",
    category: "Printing & Personalization",
    unitPrice: 16500,
    costBase: 4800,
    unit: "dia",
    description: "Impresion de tatuajes temporales personalizados con diseno del cliente.",
    hasSetup: true,
    setupCost: 2500,
  },
  {
    id: "pr-sticker-station",
    hubspotId: "",
    name: "Sticker Station",
    category: "Printing & Personalization",
    unitPrice: 14800,
    costBase: 4000,
    unit: "dia",
    description: "Estacion de stickers personalizados con disenos del evento.",
    hasSetup: true,
    setupCost: 2000,
  },
  {
    id: "pr-branding-100-vasos",
    hubspotId: "",
    name: "Branding 100 Vasos",
    category: "Printing & Personalization",
    unitPrice: 8500,
    costBase: 3000,
    unit: "paquete",
    description: "Branding personalizado en 100 vasos para evento.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-branding-producto",
    hubspotId: "",
    name: "Branding de Producto",
    category: "Printing & Personalization",
    unitPrice: 12000,
    costBase: 4500,
    unit: "paquete",
    description: "Personalizacion visual y branding completo sobre producto del cliente.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-esferas-100",
    hubspotId: "",
    name: "Esferas Transparentes 100 piezas",
    category: "Printing & Personalization",
    unitPrice: 9500,
    costBase: 3500,
    unit: "paquete",
    description: "100 esferas transparentes personalizadas con contenido interno del evento.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "pr-esferas-200",
    hubspotId: "",
    name: "Esferas Transparentes 200 piezas",
    category: "Printing & Personalization",
    unitPrice: 16000,
    costBase: 6000,
    unit: "paquete",
    description: "200 esferas transparentes personalizadas con contenido interno del evento.",
    hasSetup: false,
    setupCost: 0,
  },

  // ── Interactive Screens/Totems ────────────────────────────────
  {
    id: "it-totem-personalizado",
    hubspotId: "",
    name: "Juego Interactivo en Pantalla con Totem PERSONALIZADO",
    category: "Interactive Screens/Totems",
    unitPrice: 55000,
    costBase: 18000,
    unit: "dia",
    description: "Juego interactivo completamente personalizado con totem tactil y desarrollo a medida.",
    hasSetup: true,
    setupCost: 8000,
  },
  {
    id: "it-atrapa-objetos",
    hubspotId: "",
    name: "Juego Interactivo ATRAPA OBJETOS",
    category: "Interactive Screens/Totems",
    unitPrice: 42000,
    costBase: 14000,
    unit: "dia",
    description: "Juego interactivo en pantalla tipo atrapa objetos con branding del cliente.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "it-memorama",
    hubspotId: "",
    name: "Juego Interactivo MEMORAMA",
    category: "Interactive Screens/Totems",
    unitPrice: 42000,
    costBase: 14000,
    unit: "dia",
    description: "Juego de memorama interactivo en pantalla tactil con imagenes personalizadas.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "it-quiz",
    hubspotId: "",
    name: "Juego Interactivo QUIZ",
    category: "Interactive Screens/Totems",
    unitPrice: 42000,
    costBase: 14000,
    unit: "dia",
    description: "Quiz interactivo en pantalla tactil con preguntas y respuestas personalizadas.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "it-slots",
    hubspotId: "",
    name: "Juego Interactivo SLOTS",
    category: "Interactive Screens/Totems",
    unitPrice: 42000,
    costBase: 14000,
    unit: "dia",
    description: "Maquina tragamonedas interactiva en pantalla tactil con premios personalizados.",
    hasSetup: true,
    setupCost: 6000,
  },
  {
    id: "it-pacman",
    hubspotId: "",
    name: "Juego Interactivo TIPO PACMAN",
    category: "Interactive Screens/Totems",
    unitPrice: 45000,
    costBase: 15000,
    unit: "dia",
    description: "Juego tipo Pacman interactivo en pantalla con personajes y escenarios del cliente.",
    hasSetup: true,
    setupCost: 7000,
  },
  {
    id: "it-mesa-interactiva",
    hubspotId: "",
    name: "Juego Interactivo en Pantalla con Mesa",
    category: "Interactive Screens/Totems",
    unitPrice: 48000,
    costBase: 16000,
    unit: "dia",
    description: "Juego interactivo en mesa tactil de gran formato con experiencia inmersiva.",
    hasSetup: true,
    setupCost: 7500,
  },

  // ── Development & Services ────────────────────────────────────
  {
    id: "sv-assets-1sem",
    hubspotId: "",
    name: "Desarrollo Assets 1 semana",
    category: "Development & Services",
    unitPrice: 8500,
    costBase: 4000,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales, marcos, fondos y animaciones (1 semana).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-assets-2sem",
    hubspotId: "",
    name: "Desarrollo Assets 2 semanas",
    category: "Development & Services",
    unitPrice: 14000,
    costBase: 7000,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales con mayor complejidad (2 semanas).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-assets-3sem",
    hubspotId: "",
    name: "Desarrollo Assets 3 semanas",
    category: "Development & Services",
    unitPrice: 18000,
    costBase: 9500,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales de alta complejidad (3 semanas).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-assets-4sem",
    hubspotId: "",
    name: "Desarrollo Assets 4 semanas",
    category: "Development & Services",
    unitPrice: 22000,
    costBase: 12000,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales proyecto completo (4 semanas).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-assets-5sem",
    hubspotId: "",
    name: "Desarrollo Assets 5 semanas",
    category: "Development & Services",
    unitPrice: 25000,
    costBase: 14000,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales proyecto extenso (5 semanas).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-assets-6sem",
    hubspotId: "",
    name: "Desarrollo Assets 6 semanas",
    category: "Development & Services",
    unitPrice: 28000,
    costBase: 16000,
    unit: "paquete",
    description: "Diseno y desarrollo de assets digitales proyecto premium (6 semanas).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-desarrollo-software",
    hubspotId: "",
    name: "Desarrollo de Software",
    category: "Development & Services",
    unitPrice: 25000,
    costBase: 14000,
    unit: "paquete",
    description: "Desarrollo de software personalizado para activaciones y experiencias interactivas.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-desarrollo-electronica",
    hubspotId: "",
    name: "Desarrollo de Electronica",
    category: "Development & Services",
    unitPrice: 20000,
    costBase: 11000,
    unit: "paquete",
    description: "Desarrollo de electronica personalizada, sensores y controladores a medida.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-landing-basica",
    hubspotId: "",
    name: "Landing Page Basica",
    category: "Development & Services",
    unitPrice: 8500,
    costBase: 4000,
    unit: "paquete",
    description: "Diseno y desarrollo de landing page basica para evento o campana.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-modelado-basico",
    hubspotId: "",
    name: "Modelado Basico",
    category: "Development & Services",
    unitPrice: 8000,
    costBase: 4000,
    unit: "paquete",
    description: "Modelado 3D basico para hologramas, AR o contenido visual.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-modelado-intermedio",
    hubspotId: "",
    name: "Modelado Intermedio",
    category: "Development & Services",
    unitPrice: 14000,
    costBase: 7500,
    unit: "paquete",
    description: "Modelado 3D intermedio con texturas y animaciones para experiencias interactivas.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-modelado-avanzado",
    hubspotId: "",
    name: "Modelado Avanzado",
    category: "Development & Services",
    unitPrice: 22000,
    costBase: 12000,
    unit: "paquete",
    description: "Modelado 3D avanzado hiperrealista con animaciones complejas y renderizado.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-hora-extra",
    hubspotId: "",
    name: "Hora Extra",
    category: "Development & Services",
    unitPrice: 3500,
    costBase: 1800,
    unit: "hora",
    description: "Hora extra de operacion del equipo y personal en el evento.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-personal-promocion",
    hubspotId: "",
    name: "Personal de Promocion GIO",
    category: "Development & Services",
    unitPrice: 5500,
    costBase: 2800,
    unit: "persona",
    description: "Personal de promocion y activacion proporcionado por GIO.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-fabricacion-bastones",
    hubspotId: "",
    name: "Fabricacion Bastones",
    category: "Development & Services",
    unitPrice: 12000,
    costBase: 6000,
    unit: "paquete",
    description: "Fabricacion de bastones personalizados para activaciones y displays.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-filtro-ar-instagram",
    hubspotId: "",
    name: "Filtro AR Instagram",
    category: "Development & Services",
    unitPrice: 15000,
    costBase: 7500,
    unit: "paquete",
    description: "Desarrollo de filtro de realidad aumentada personalizado para Instagram.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-filtro-ar-snapchat",
    hubspotId: "",
    name: "Filtro AR Snapchat",
    category: "Development & Services",
    unitPrice: 15000,
    costBase: 7500,
    unit: "paquete",
    description: "Desarrollo de filtro de realidad aumentada personalizado para Snapchat.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-estructura-personalizada",
    hubspotId: "",
    name: "Estructura Personalizada",
    category: "Development & Services",
    unitPrice: 18000,
    costBase: 9500,
    unit: "paquete",
    description: "Diseno y fabricacion de estructura fisica personalizada para activaciones.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "sv-levantamiento-holograma",
    hubspotId: "",
    name: "Levantamiento Contenido Holograma",
    category: "Development & Services",
    unitPrice: 12000,
    costBase: 6000,
    unit: "paquete",
    description: "Produccion y levantamiento de contenido 3D para proyeccion holografica.",
    hasSetup: false,
    setupCost: 0,
  },

  // ── Viaticos ──────────────────────────────────────────────────
  {
    id: "vi-cdmx",
    hubspotId: "",
    name: "Viaticos CDMX",
    category: "Viaticos",
    unitPrice: 2800,
    costBase: 2200,
    unit: "persona",
    description: "Viaticos para personal operativo en eventos dentro de CDMX y area metropolitana.",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "vi-foraneo",
    hubspotId: "",
    name: "Viaticos Foraneo",
    category: "Viaticos",
    unitPrice: 5500,
    costBase: 4500,
    unit: "persona",
    description: "Viaticos para personal en eventos foraneos (vuelo, hotel, alimentos).",
    hasSetup: false,
    setupCost: 0,
  },
  {
    id: "vi-cancun",
    hubspotId: "",
    name: "Viaticos Cancun",
    category: "Viaticos",
    unitPrice: 7500,
    costBase: 6200,
    unit: "persona",
    description: "Viaticos premium para eventos en zona Cancun y Riviera Maya.",
    hasSetup: false,
    setupCost: 0,
  },
];

// ── Helper Functions ──────────────────────────────────────────

export function getProductsByCategory(category: ProductCategory): Product[] {
  return PRODUCTS_CATALOG.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS_CATALOG.find((p) => p.id === id);
}

export function searchProducts(query: string): Product[] {
  const lower = query.toLowerCase();
  return PRODUCTS_CATALOG.filter(
    (p) =>
      p.name.toLowerCase().includes(lower) ||
      p.description.toLowerCase().includes(lower) ||
      p.category.toLowerCase().includes(lower)
  );
}
